# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8181:8181"
    depends_on:
      - db
  db:
    image: mysql:latest
    #env_file:
     # - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"



#env_file:
 #     - .env
  #  environment:
    #  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     # MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
